### ISSUE TITLE
Ultimate Mortal Kombat - graphical and stability issues

### ISSUE THREAD

**Issue by MojoJojoDojo** [ahezard/nds-bootstrap#493]
### Your console
New 2DS XL
### CFW and configuration

ell us which CFW do you have: 
Luma
nds-bootstrap version:
The latest one - v0.14.1
### Tell us which versions you are using:
Release
### If this issue only affects a certain game, which game is it?
Ultimate Mortal Kombat
### Expected behavior
Slowdowns are expected if the blood option is on using multiplayer/single player.
Graphics should appear properly.
No stability issues. 
Tell us what should happen:
No graphical issues or stability ones.
### Actual behavior
Tell us what happens instead:
The game graphics flicker and in rare cases the game might freeze/lock itself.
The game freezes or locks itself all the time if you try to play the game's online multiplayer mode
using AltWFC or another alternative WiFi service (This behavior happened in a build that is previous to version 0.14.1)
The game will freeze at the character select.
### Steps to reproduce
Non Wi-FI issue:
1.Go to the Single Player mode
2.Choose a character.
3.Play an actual VS match
You will see that the graphics flicker sometimes.
Wi-Fi issue:
1.Go to Nintendo Wi-FI Connection
2.Play with another player
3.Try to choose a character
In that point the game will freeze.
### Other notes
I Didn't check how the Local Wireless mode works.
I still didn't check the Wi-Fi related problem in the latest nds-bootstrap version (I need someone to play against).
I played the game both in TWL and NTR speeds.

**Comment by dubbz82** [comment]
Thanks.  This game has been brought up on discord on a couple occasions.  Good to have it properly tracked here.  I knew about the flicker but hadn't tried WiFi and hadn't yet experienced the freezing.

**Comment by MojoJojoDojo** [comment]
Something of note , this game is the most lag-prone game I ever saw on the DS.
Even the TWL setting wont help the lags much.

**Comment by dubbz82** [comment]
Can you try this with a newer build?  This should be better now (still not completely fixed I believe, but much better than it was in early January)

**Comment by ahezard** [comment]
could be linked to #554 that have been fixed. Please retest with the latest nightly.

**Comment by dubbz82** [comment]
I don't have anyone to wifi against, but the actual gameplay issues are entirely gone as far as I can tell.  Not sure if we should still leave this open for the wifi issues until someone can test this?

**Comment by MojoJojoDojo** [comment]
I tried to play UMK but all I get is a black screen now.
Is it something in my settings or something? I dont remember if i NoSSL'ed patched my game.

**Comment by dubbz82** [comment]
multiplayer issues may be related to #553 ?

**Comment by MojoJojoDojo** [comment]
I am still getting a black screen when i launch the rom.
I am using a USA Rom.

**Comment by ahezard** [comment]
There is a patch "fix bug" in the wood code here : https://github.com/ahezard/woodrpg_forwarder/blob/e0280c91b21e28443c23f98a171012ef8a301b0c/akloader/arm9/source/patches_cm.cpp

**Comment by RocketRobz** [comment]
Reportedly works fine on latest nightly, by RetroGameFan.
