### ISSUE TITLE
Bomberman 2: Battle Mode not working

### ISSUE THREAD

**Issue by gingerbeardman** [ahezard/nds-bootstrap#710]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [X]  (No CFW) Unlaunch only _[1.9]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[0.21.2]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

3430 - Bomberman 2 (EU)

(SDK v4 game)

### Expected behaviour

- Should have sound

### Actual behaviour

- No sound
- white screen starting Battle Mode 

### Steps to reproduce

1. confirm sound in TwilightMenu
2. launch ROM
3. confirm no sound in game
4. confirm white screen starting Battle Mode

**Comment by RocketRobz** [comment]
Sound plays for me, but I'm able to reproduce the white screen crash.

**Comment by gingerbeardman** [comment]
Regarding sound, how does your setup differ to mine?

I definitely have no sound.

**Comment by gingerbeardman** [comment]
Update: on a hunch I used https://github.com/mondul/HiyaCFW-Helper to redo my SD card and no sound is working. No idea what was missing or wrong.

**Comment by ahezard** [comment]
Probably linked to #259

**Comment by RocketRobz** [comment]
The crashing is fixed, but the mode still doesn't load.
The game just reboots.

**Comment by RocketRobz** [comment]
Fixed in f66355f7

**Comment by Headmetalz** [comment]
Hello,

3430 - Bomberman 2 (EU)

Found another issue, not sure if only on my side: 

When selecting "Battle Mode", I get an exception error and need to shut down my 3ds. After turning it on again, and selecting Twilight Menu, the application loads and goes directly to the battle mode menu of the game, as if the exception error did not occur before.

I'm using a new 3ds XL. CFW Luma 3ds and my device is an SD Card. Newest releases of Twilight Menu and ndsbootstrap downloaded.

Sorry if i should not comment here, I just found the topic by the search icon and I'm new to this.

**Comment by RocketRobz** [comment]
@Headmetalz Please update Luma3DS.

**Comment by Headmetalz** [comment]
Thank you so much for the fast reply, and sorry for not answering it before. 

It worked like a charm.

Sorry for the trouble and thank you so much again!

**Comment by aisak1997** [comment]
Hi guys I'm new here but the same problem in my case, Im still don't know what to do becasue the screen goes white after selecting the battlemode. have you found a solution or what to do exactly, cuz im not good at computers and softwares but im trying to solve it.

**Comment by Headmetalz** [comment]
Hello,

As far as I know, as of the new versions of Twilight Menu, the problem is
already solved. However, if you still face this problem, you have to update
Luma3ds for it to work correctly.

Also, check if Twilight Menu is updated via the Universal Updater homebrew
app.

Good luck.

Em sex., 18 de fev. de 2022 às 13:12, aisak1997 ***@***.***>
escreveu:
